export interface TemaLinktree {
  kode: string;
  nama: string;
  deskripsi: string;
  latar: string;
  warna_primer: string;
  warna_teks: string;
  warna_teks_sekunder: string;
  warna_tombol_latar: string;
  warna_tombol_teks: string;
  warna_tombol_border: string;
  font: string;
  border_radius_tombol: string;
  gaya_tombol: "solid" | "outline" | "ghost" | "glass";
  backdrop_blur?: boolean;
}

export const DAFTAR_TEMA: TemaLinktree[] = [
  {
    kode: "minimal-light",
    nama: "Minimal Light",
    deskripsi: "Putih bersih, tipografi elegan, shadcn-style",
    latar: "#FFFFFF",
    warna_primer: "#18181B",
    warna_teks: "#18181B",
    warna_teks_sekunder: "#71717A",
    warna_tombol_latar: "#F4F4F5",
    warna_tombol_teks: "#18181B",
    warna_tombol_border: "#E4E4E7",
    font: "Inter",
    border_radius_tombol: "0.5rem",
    gaya_tombol: "outline",
  },
  {
    kode: "minimal-dark",
    nama: "Minimal Dark",
    deskripsi: "Hitam elegan, cocok untuk brand profesional",
    latar: "#09090B",
    warna_primer: "#FAFAFA",
    warna_teks: "#FAFAFA",
    warna_teks_sekunder: "#A1A1AA",
    warna_tombol_latar: "#18181B",
    warna_tombol_teks: "#FAFAFA",
    warna_tombol_border: "#27272A",
    font: "Inter",
    border_radius_tombol: "0.5rem",
    gaya_tombol: "outline",
  },
  {
    kode: "aurora",
    nama: "Aurora",
    deskripsi: "Gradien ungu-biru aurora borealis, modern & vibrant",
    latar: "linear-gradient(135deg, #0F0C29, #302B63, #24243E)",
    warna_primer: "#A78BFA",
    warna_teks: "#FFFFFF",
    warna_teks_sekunder: "#C4B5FD",
    warna_tombol_latar: "rgba(167, 139, 250, 0.15)",
    warna_tombol_teks: "#FFFFFF",
    warna_tombol_border: "rgba(167, 139, 250, 0.4)",
    font: "Plus Jakarta Sans",
    border_radius_tombol: "0.75rem",
    gaya_tombol: "glass",
  },
  {
    kode: "sunset",
    nama: "Sunset",
    deskripsi: "Gradien oranye-merah muda hangat seperti matahari terbenam",
    latar: "linear-gradient(135deg, #FF6B6B, #FE9F43, #FF6B6B)",
    warna_primer: "#FFFFFF",
    warna_teks: "#FFFFFF",
    warna_teks_sekunder: "rgba(255,255,255,0.8)",
    warna_tombol_latar: "rgba(255,255,255,0.2)",
    warna_tombol_teks: "#FFFFFF",
    warna_tombol_border: "rgba(255,255,255,0.4)",
    font: "Poppins",
    border_radius_tombol: "9999px",
    gaya_tombol: "glass",
  },
  {
    kode: "ocean-depth",
    nama: "Ocean Depth",
    deskripsi: "Gradien biru teal dalam seperti lautan, tenang & premium",
    latar: "linear-gradient(180deg, #0D3B66, #1A6985, #0D3B66)",
    warna_primer: "#5CE1E6",
    warna_teks: "#FFFFFF",
    warna_teks_sekunder: "rgba(255,255,255,0.7)",
    warna_tombol_latar: "rgba(92, 225, 230, 0.15)",
    warna_tombol_teks: "#5CE1E6",
    warna_tombol_border: "rgba(92, 225, 230, 0.35)",
    font: "DM Sans",
    border_radius_tombol: "0.5rem",
    gaya_tombol: "outline",
  },
  {
    kode: "neon-night",
    nama: "Neon Night",
    deskripsi: "Hitam pekat dengan aksen neon hijau, cyberpunk aesthetic",
    latar: "#0A0A0A",
    warna_primer: "#00FF87",
    warna_teks: "#FFFFFF",
    warna_teks_sekunder: "#A0A0A0",
    warna_tombol_latar: "rgba(0, 255, 135, 0.1)",
    warna_tombol_teks: "#00FF87",
    warna_tombol_border: "#00FF87",
    font: "Space Grotesk",
    border_radius_tombol: "0.25rem",
    gaya_tombol: "outline",
  },
  {
    kode: "pastel-dream",
    nama: "Pastel Dream",
    deskripsi: "Lembut pastel merah muda dan ungu, aesthetic & feminim",
    latar: "linear-gradient(135deg, #FFF0F3, #F8EDFF)",
    warna_primer: "#D63384",
    warna_teks: "#3D2C3D",
    warna_teks_sekunder: "#8B6A8B",
    warna_tombol_latar: "#FFFFFF",
    warna_tombol_teks: "#D63384",
    warna_tombol_border: "#F0B8D0",
    font: "DM Serif Display",
    border_radius_tombol: "9999px",
    gaya_tombol: "solid",
  },
  {
    kode: "forest",
    nama: "Forest",
    deskripsi: "Hijau alam yang dalam, cocok untuk brand organik & nature",
    latar: "#1A2E1A",
    warna_primer: "#6FCF97",
    warna_teks: "#E8F5E9",
    warna_teks_sekunder: "#A5D6A7",
    warna_tombol_latar: "rgba(111, 207, 151, 0.15)",
    warna_tombol_teks: "#6FCF97",
    warna_tombol_border: "rgba(111, 207, 151, 0.3)",
    font: "Lato",
    border_radius_tombol: "0.5rem",
    gaya_tombol: "outline",
  },
  {
    kode: "gold-luxury",
    nama: "Gold Luxury",
    deskripsi: "Hitam & emas, kesan mewah dan premium tinggi",
    latar: "#0C0C0C",
    warna_primer: "#D4AF37",
    warna_teks: "#FFFFFF",
    warna_teks_sekunder: "#B8A370",
    warna_tombol_latar: "rgba(212, 175, 55, 0.1)",
    warna_tombol_teks: "#D4AF37",
    warna_tombol_border: "#D4AF37",
    font: "Cormorant Garamond",
    border_radius_tombol: "0.25rem",
    gaya_tombol: "outline",
  },
  {
    kode: "brutalist",
    nama: "Brutalist",
    deskripsi: "Border hitam tebal, warna blok solid, typography bold",
    latar: "#FFFBF0",
    warna_primer: "#000000",
    warna_teks: "#000000",
    warna_teks_sekunder: "#333333",
    warna_tombol_latar: "#FFE135",
    warna_tombol_teks: "#000000",
    warna_tombol_border: "#000000",
    font: "Space Grotesk",
    border_radius_tombol: "0",
    gaya_tombol: "solid",
  },
  {
    kode: "glass-morphism",
    nama: "Glass Morphism",
    deskripsi: "Blur glassmorphism dengan gradien biru-ungu, modern UI trend",
    latar: "linear-gradient(135deg, #1E1E2E, #2D2B55)",
    warna_primer: "#FFFFFF",
    warna_teks: "#FFFFFF",
    warna_teks_sekunder: "rgba(255,255,255,0.6)",
    warna_tombol_latar: "rgba(255,255,255,0.08)",
    warna_tombol_teks: "#FFFFFF",
    warna_tombol_border: "rgba(255,255,255,0.2)",
    font: "Inter",
    border_radius_tombol: "0.75rem",
    gaya_tombol: "glass",
    backdrop_blur: true,
  },
  {
    kode: "retro-wave",
    nama: "Retro Wave",
    deskripsi: "Synthwave 80s, gradien pink-ungu neon, retro aesthetic",
    latar: "linear-gradient(180deg, #0D0221, #1A0536)",
    warna_primer: "#FF71CE",
    warna_teks: "#FFFFFF",
    warna_teks_sekunder: "#B388FF",
    warna_tombol_latar: "rgba(255, 113, 206, 0.1)",
    warna_tombol_teks: "#FF71CE",
    warna_tombol_border: "#FF71CE",
    font: "Orbitron",
    border_radius_tombol: "0.25rem",
    gaya_tombol: "outline",
  },
  {
    kode: "earth-tone",
    nama: "Earth Tone",
    deskripsi: "Warna tanah hangat, cokelat & krem, cocok untuk kreator lifestyle",
    latar: "#F5EFE6",
    warna_primer: "#8B5E3C",
    warna_teks: "#3D1F00",
    warna_teks_sekunder: "#7A5C42",
    warna_tombol_latar: "#EDE0D4",
    warna_tombol_teks: "#5C3D1E",
    warna_tombol_border: "#C4A882",
    font: "Playfair Display",
    border_radius_tombol: "0.5rem",
    gaya_tombol: "solid",
  },
  {
    kode: "arctic",
    nama: "Arctic",
    deskripsi: "Putih biru es, bersih & minimalis, cocok untuk tech & startup",
    latar: "linear-gradient(180deg, #E8F4FD, #FFFFFF)",
    warna_primer: "#0077B6",
    warna_teks: "#03045E",
    warna_teks_sekunder: "#4895EF",
    warna_tombol_latar: "#FFFFFF",
    warna_tombol_teks: "#0077B6",
    warna_tombol_border: "#90E0EF",
    font: "DM Sans",
    border_radius_tombol: "9999px",
    gaya_tombol: "outline",
  },
  {
    kode: "monochrome-bold",
    nama: "Monochrome Bold",
    deskripsi: "Hitam putih bold, tipografi besar, editorial modern",
    latar: "#FFFFFF",
    warna_primer: "#000000",
    warna_teks: "#000000",
    warna_teks_sekunder: "#555555",
    warna_tombol_latar: "#000000",
    warna_tombol_teks: "#FFFFFF",
    warna_tombol_border: "#000000",
    font: "Syne",
    border_radius_tombol: "0.375rem",
    gaya_tombol: "solid",
  },
  // ── New V2 Themes ──────────────────────────────────────────────────────────
  {
    kode: "dark-glass",
    nama: "Dark Glass",
    deskripsi: "Glassmorphism gelap transparan dengan latar gradien premium",
    latar: "linear-gradient(135deg, #111827, #1f2937, #111827)",
    warna_primer: "#38BDF8",
    warna_teks: "#F3F4F6",
    warna_teks_sekunder: "#9CA3AF",
    warna_tombol_latar: "rgba(255, 255, 255, 0.05)",
    warna_tombol_teks: "#F3F4F6",
    warna_tombol_border: "rgba(255, 255, 255, 0.1)",
    font: "Outfit",
    border_radius_tombol: "1rem",
    gaya_tombol: "glass",
    backdrop_blur: true,
  },
  {
    kode: "retro-cyber",
    nama: "Retro Cyberpunk",
    deskripsi: "Tema retro dengan warna kontras neon cyan & magenta",
    latar: "linear-gradient(135deg, #090015, #17002b)",
    warna_primer: "#FF007F",
    warna_teks: "#00F0FF",
    warna_teks_sekunder: "#FF007F",
    warna_tombol_latar: "rgba(0, 240, 255, 0.07)",
    warna_tombol_teks: "#00F0FF",
    warna_tombol_border: "#FF007F",
    font: "Orbitron",
    border_radius_tombol: "0px",
    gaya_tombol: "outline",
  },
  {
    kode: "warm-clay",
    nama: "Warm Clay",
    deskripsi: "Warna peach hangat, lembut tanah liat, ramah & estetik",
    latar: "#FAF6F0",
    warna_primer: "#D97706",
    warna_teks: "#451A03",
    warna_teks_sekunder: "#78350F",
    warna_tombol_latar: "#FDE68A",
    warna_tombol_teks: "#78350F",
    warna_tombol_border: "#F59E0B",
    font: "Outfit",
    border_radius_tombol: "1.25rem",
    gaya_tombol: "solid",
  },
  {
    kode: "brutalist-dark",
    nama: "Brutalist Dark",
    deskripsi: "Gaya brutalist gelap dengan warna latar pekat dan border tegas",
    latar: "#121212",
    warna_primer: "#ADFA1D",
    warna_teks: "#FFFFFF",
    warna_teks_sekunder: "#A1A1AA",
    warna_tombol_latar: "#ADFA1D",
    warna_tombol_teks: "#000000",
    warna_tombol_border: "#FFFFFF",
    font: "Space Grotesk",
    border_radius_tombol: "0.25rem",
    gaya_tombol: "solid",
  },
];
